//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catálogo_de_Empleados_Rosa_Icela_Contreras_Ocampo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_ITSEntities : DbContext
    {
        public DB_ITSEntities()
            : base("name=DB_ITSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeesRosa> EmployeesRosa { get; set; }
        public virtual DbSet<PositionsRosa> PositionsRosa { get; set; }

        public System.Data.Entity.DbSet<Catálogo_de_Empleados_Rosa_Icela_Contreras_Ocampo.Models.EmployeeViewModel> EmployeeViewModels { get; set; }
    }
}
