//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catálogo_de_Empleados_Rosa_Icela_Contreras_Ocampo
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeesRosa
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string RFC { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual PositionsRosa PositionsRosa { get; set; }
    }
}
